### ISSUE TITLE
error loading plugin, when running prettier from terminal

### ISSUE THREAD

**Issue by ottodevs** [so1ve/prettier-plugin-taplo#32]
When trying to run prettier from terminal this error happens:

```sh
$ prettier -uw '**/*.*'
[error] No "exports" main defined in
~/sample_project/node_modules/prettier-plugin-taplo/package.json
imported from ~/sample_project/noop.js
error: script "format" exited with code 1 (SIGHUP)
```

I researched about the error and apparently it is needed to define a main (default item) for it.

I am using prettier 3 and loading the pluigin from prettier config. In vscode it works correctly, it just fails when trying from terminal.

**Comment by so1ve** [comment]
Released 0.0.1
