### ISSUE TITLE
Run format in main thread

### ISSUE THREAD

**Issue by fisker** [so1ve/prettier-plugin-taplo#37]
Come cross this repo, and see that we are formatting code in a worker.

1. We can actually do format in `parse`, 

```js
{
  parse: async () => ({formatted: await format(...)})`,
  print: ({node: {formatted}}) => formatted
}
```

2. It's undocumented, but `print` actually support returns a promise, it will work as long as you don't call `print` recursively.

**Comment by so1ve** [comment]
Wow looks pretty cool 👍 I'll check it later, thanks for your notice!
